version: '3.8'

networks:
  lore_service_network:
    driver: bridge

services:
  postgres-user-db:
    image: 'library/postgres:16.0'
    container_name: postgres-user-db
    env_file:
      - database.env
    restart: always
    ports:
      - 5432:5432
    networks:
      - lore_service_network

  keycloak:
    container_name: keycloak-server
    image: 'quay.io/keycloak/keycloak:latest'
    command:
      - "start-dev"
    env_file:
      - keycloak.env
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-configs.json
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - lore_service_network
    volumes:
      - ./imports:/opt/jboss/keycloak/imports

